### PR TITLE
added GA4GH Feature attributes parser

### PR DESCRIPTION
**Pull request by akmorrow13**

### CODE REVIEW

**Comment by heuermh** [comment]
Thank you, @akmorrow13!  There are some minor code style changes I'd suggest, but I'll make those changes in a follow-up pull request instead.

**Comment by akmorrow13** [comment]
Thanks for the help @heuermh!

**Comment by heuermh** [comment]
Will you need a release here before changes due to bdg-formats 0.12.0/ADAM 0.26.0?

**Comment by akmorrow13** [comment]
@heuermh it looks like this is only dependent on bdg-formats. Were you planning on waiting to cut a release on bdg-convert after bdg-formats is cut? What is the timeline for that?

**Comment by heuermh** [comment]
This Wednesday for bdg-formats 0.12.0 release, which contains binary incompatible changes to `AlignmentRecord` and `RecordGroup`s, ADAM 0.26.0 release immediately thereafter, which contains binary incompatible changes to all the *RDD classes, among other things.

**Comment by akmorrow13** [comment]
Oh my, that will involve a big rebase. Could we do a release before those changes?

**Comment by heuermh** [comment]
Yeah, I plan to make a pull requests for Avocado and Mango, similar to https://github.com/bigdatagenomics/cannoli/pull/153, to help, but yeah, it might make sense to cut 0.5.0 against bdg-formats 0.11.4/ADAM 0.25.0 before doing so.

**Comment by heuermh** [comment]
Tomorrow I will sequence releases in this order:
1. bdg-convert 0.5.0 (depends on bdg-formats 0.11.4)
2. bdg-formats 0.12.0
3. adam 0.26.0
4. cannoli 0.4.0
5. update bdg-convert to bdg-formats 0.12.0
6. release bdg-convert 0.6.0 (depends on bdg-formats 0.12.0)
7. pull request mango with bdg-convert 0.6.0/bdg-formats 0.12.0/adam 0.26.0 changes

**Comment by akmorrow13** [comment]
Thanks for all the help @heuermh! Let me know if I can be of service.

**Pull request merged**
